services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: db-identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity@1234
    ports:
      - "5445:5432"
    volumes:
      - db_business_vol:/var/lib/postgresql/data

volumes:
  db_business_vol: