spring:
  application:
    name: identity
  config:
    import: "configserver:http://localhost:1688"

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5445/db-identity
    username: identity
    password: identity@1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

logging:
  level:
    org.springframework.security: trace
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

