server:
  port: 1688
spring:
  application:
    name: config-server
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyzhiaa/yelp-config.git
          default-label: main
          search-paths: "/service/**"
#        native:
#          search-locations:
#            - file:///D:/Decompose-By-Subdomain/Decompose-By-Subdomain/YelpMsConfig
#            - file:///D:/Decompose-By-Subdomain/Decompose-By-Subdomain/YelpMsConfig/service/{application}
eureka:
  client:
    serviceUrl:
      #      defaultZone: http://service-registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/