server:
  port: 1688
spring:
  application:
    name: config-server
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyzhiaa/decompose-yelp.git
          default-label: main
          search-paths: "/service/**"
#        native:
#          search-locations:
#            - file:///D:/Decompose-By-Subdomain/Decompose-By-Subdomain/YelpMsConfig
#            - file:///D:/Decompose-By-Subdomain/Decompose-By-Subdomain/YelpMsConfig/service/{application}
